# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOa-mR_tL61Ob-qlBCWp2n_64-EVoiFi
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Title
st.title("Impact of Handwashing on Mortality")

# Description
st.write("This app analyzes how handwashing reduced mortality rates.")

# Load data
df = pd.read_csv("yearly_deaths_by_clinic-1.csv")

# Ensure 'date' and 'proportion_deaths' columns exist in df
# Create a 'date' column from the 'Year' column
df['date'] = pd.to_datetime(df['Year'], format='%Y')

# Calculate 'proportion_deaths'
df['proportion_deaths'] = df['Deaths'] / df['Birth']

# Handwashing started around 1847
handwashing_start = pd.to_datetime('1847-01-01')

# Plot proportion of deaths over time for each clinic
plt.figure(figsize=(12, 6))
for clinic in df['Clinic'].unique():
    clinic_df = df[df['Clinic'] == clinic]
    plt.plot(clinic_df['date'], clinic_df['proportion_deaths'], label=clinic)

plt.axvline(handwashing_start, color='r', linestyle='--', label='Handwashing Introduced (1847)')

plt.xlabel('Date')
plt.ylabel('Proportion of Deaths')
plt.title('Proportion of Deaths Over Time by Clinic')
plt.legend()
plt.grid(True)
plt.show()

st.write("After the introduction of handwashing, mortality rates dropped significantly, showing a clear improvement in patient outcomes. ")